### ISSUE TITLE
[Question] Fetch vs XHR adapter

### ISSUE THREAD

**Issue by OzairP** [apicase/core#12]
Since both adapter adhere to the same contract, is there any reason to use the `fetch` adapter over the `XHR` adapter?

Thanks!

**Comment by Kelin2025** [comment]
To be honest, there are no difference   
But only `fetch` adapter uses polyfill for Node.js

**Comment by Piterden** [comment]
Btw, I had caught the strange bug with fetch in chrome. It was an empty response. I was had to use XHR, instead of fetch.
