### ISSUE TITLE
Uncaught (in promise) TypeError: retry is not a function

### ISSUE THREAD

**Issue by mblonyox** [apicase/core#19]
I try to write a fail hook with a retry, but there is no retry function in state passed to the 'fail' hook.

**Comment by Kelin2025** [comment]
Oh, I forgot about `retry` after hooks refactoring.  
I'll fix it soon

**Comment by Kelin2025** [comment]
Fixed in [**v0.13**](https://github.com/apicase/core/releases/tag/v0.13.0)  
Note that you might get recursive request 😄

**Comment by mblonyox** [comment]
wow thank you so much.

Actually i use recursive request inside the fail hook, then throw the result to done methods if it is success or put it in the next method.
I guess, i'll jus gonna change it again.
