### ISSUE TITLE
Supported browsers in readme

### ISSUE THREAD

**Issue by ThomasKlessen** [apicase/core#20]
It would be nice if you include some informations about supported browsers or required polyfills into the readme. 
At least i was not able to find this information.

**Comment by Kelin2025** [comment]
Yep, I'll do it on weekends

**Comment by Kelin2025** [comment]
Hey, I added some info about polyfills and browsers. [click here](https://github.com/apicase/core/blob/master/README.md#browser-supports--restrictions)
