### ISSUE TITLE
CORS Support?

### ISSUE THREAD

**Issue by contrarianaupong** [apicase/core#22]
Is it possible to call the api from external server? I got the same origin error when trying external url.

Request mode is "same-origin" but the URL's origin is not same as the request origin

**Comment by Kelin2025** [comment]
Do you use fetch adapter? You can use 
```diff
  doRequest({
    adapter: fetch,
    url: 'smth',
+   mode: 'cors'
  })
```
Like native fetch works: https://developer.mozilla.org/en-US/docs/Web/API/Request/mode

**Comment by contrarianaupong** [comment]
It works now. Thank you.

**Comment by Kelin2025** [comment]
No problem ;)
