### ISSUE TITLE
Refactor request flow

### ISSUE THREAD

**Issue by Kelin2025** [apicase/core#23]
Now it spawns promises that cannot be `.catch()` ed. Need to fix and create one queue

**Comment by Kelin2025** [comment]
Fixed

**Comment by TomoGlavas** [comment]
Sorry for commenting on a closed issue, but I couldn't find anything in the docs about this.

I am seeing `Uncaught (in promise) TypeError: Failed to fetch` with `"@apicase/core": "^0.16.0-beta.2"`.

How should I catch failed requests using `ApiTree` and `ApiService`?

Tyvm
