### ISSUE TITLE
Need help for supporting IE11 with vue

### ISSUE THREAD

**Issue by AndreaMinato** [apicase/core#25]
Hi i'm trying to replace my api layer done with axios to use apicase on a project that is going to be quite big.
It all works like  a charm on chrome/firefox/edge and safari but i have some problem with IE.

I have read the documentationon your [readme](https://github.com/apicase/core#browser-supports--restrictions) but i can't figure out how to make it work on IE.

I'm using vueJs (vue cli 3.0.1) as the frontend framework and they have a dedicated page in their [documentation here](https://cli.vuejs.org/guide/browser-compatibility.html#polyfills).

I have tried all 3 the options provided by the vue team and I event tried to link the script tag in the index file but Ie alway come up with this error (promises and fetch)

`SCRIPT1002: Syntax error`
`app.js (812,23)`

```javascript
/***/ "./node_modules/@apicase/adapter-fetch/index.js":
/*!******************************************************!*\
  !*** ./node_modules/@apicase/adapter-fetch/index.js ***!
  \******************************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
const fetch =
  (typeof window === 'object' && window.fetch) || __webpack_require__(/*! node-fetch */ "./node_modules/node-fetch/browser.js")
const pathToRegexp = __webpack_require__(/*! path-to-regexp */ "./node_modules/@apicase/adapter-fetch/node_modules/path-to-regexp/index.js")

var _FormData = typeof FormData !== 'undefined' ? FormData : function() {}

const parseUrl = url => { /// <--- HERE IS THE ERROR
  let origin = ''
  let pathname = ''
  if (url.indexOf('://') > -1) {
    const res = url.match('(^(?:(?:.*?)?//)?[^/?#;]*)(.*)')
    origin = res[1]
    pathname = res[2]
  } else {
    pathname = url
  }
  return { origin, pathname }
}

const compilePath = (url, params) => pathToRegexp.compile(url)(params)


//other code from the lib
```

As i can see it seems that it fails with an arrow function.

What could I be wrong?

**Comment by Kelin2025** [comment]
Apicase adapters sources are published "as is" so they are not transpiled.  
It seems that vue-cli has [`transpileDependencies`](https://cli.vuejs.org/config/#transpiledependencies) option so you can add `@apicase/adapter-fetch` to transpile it

**Comment by AndreaMinato** [comment]
I managed to get them compiled modifying some files in my project.

I'm going to post them here to help if someday somebody will face the same problem.

### Main problem
**vue.config.js**
In the `transpileDependencies` dependencies option I added `@apicase`, i noticed that with the nested path `@apicase/adapter-fetch` it does not work, it may be a problem with `@vue-cli`
Later i found the same problem with `delightful-bus` that is a dependency of `@apicase` so I added it in the same way.

```js
module.exports = {
   //...

   transpileDependencies: ["@apicase", "delightful-bus"],

   //...
};
```
In order to make vue transpile correctly the dependencies in the babel.config.js is needed a tweak.
[as commented in this issue](https://github.com/vuejs/vue-cli/issues/1248#issuecomment-396043977)

**babel.config.js**
```js
// hack to enforce transformation to commonjs
process.env.VUE_CLI_BABEL_TRANSPILE_MODULES = true;
module.exports = {
   //...
}
```
This *solved* the main problem with `adapter-fetch` not being transpiled

### Fetch polyfill
Since it is kinda related i will post also my solution to include the fetch polyfill
I used the `useBuiltIns: "entry"` option in the `babel.config.js` file, installed the `fetch-polyfill` and then imported in my `main.js` file

**babel.config.js**
```js
// hack to enforce transformation to commonjs
process.env.VUE_CLI_BABEL_TRANSPILE_MODULES = true;

module.exports = {
  presets: [
    [
      "@vue/app",
      {
        useBuiltIns: "entry"
      }
    ]
  ]
};
```
**npm command**
```
npm install whatwg-fetch --save
```
**main.js**
```javascript
import "whatwg-fetch";

import Vue from "vue";

//....
```
This is what I found to sucessfully include the fetch polyfill in my project, it may be worth pointing that it could be another way instead of using `builtIn: entry` and modifying the `main.js` and is documented [here](https://cli.vuejs.org/guide/browser-compatibility.html#usebuiltins-usage) but I didn't have time for that.

### Nanoutils
Now I'm facing a problemi with `nanoutils` that uses some arrays prototype like `findIndex` which are not supported in IE
I have read that `nanoutils` is another lib created by @Kelin2025 but as I can see from the [docs](https://github.com/nanoutils/nanoutils#basic-ideas) it should not be transpiled since it's written without ES6 code just to not worry about backward compatibility.
What am I missing?

**Comment by Kelin2025** [comment]
Oh, vue-cli, why so many problems 😴   

#### Problem
I don't want to transpile sources and resolve dependencies just because you'll get tons of code duplications (seems that nobody cares about it and that's why our bundles weigh more than Sun). It's especially problematic for Apicase because it has at least 3 packages you'll use (core, some adapter and services)  
My posts about problems with building libraries:
- [Writing JS libraries less than 1TB size](https://medium.com/@kelin2025/writing-js-libraries-less-than-1tb-size-6342da0c006a)
- [How to write and build JS libraries in 2018](https://medium.com/@kelin2025/so-you-wanna-use-es6-modules-714f48b3a953)

#### Nanoutils
That's true, Nanoutils are not transpiled because it's written in order to be compatible with old environments without compilation. It doesn't contain ES6 features at all ([example](https://unpkg.com/nanoutils@0.0.28/lib/all/index.js))  
Seems like some of us forgot about it. But I don't maintain this library now
cc @Beraliv 

#### Delightful-bus
About delightful-bus.. I think I'll remove it from my project later because it's a bicycle 😄  

---

Anyway, thank you for the issue and explanation. If you don't have any questions, I'll close this issue

**Comment by Beraliv** [comment]
@AndreaMinato create a separate issue in [here](https://github.com/nanoutils/nanoutils/issues)

**Comment by Beraliv** [comment]
@AndreaMinato [nanoutils@0.0.29](https://www.npmjs.com/package/nanoutils/v/0.0.29) is available now, you can update it and it should work just fine!

If you have other issues, please describe them step by step, and create issues in a respective [repo](https://github.com/nanoutils/nanoutils)

**Comment by Kelin2025** [comment]
Hey, sorry for the delay.  
I'll update dependency after [this bug fix](https://github.com/nanoutils/nanoutils/issues/130)

**Comment by Kelin2025** [comment]
Finally, it's fixed  
@AndreaMinato please run `yarn add @apicase/core@latest` or `npm install @apicase/core@latest`
