### ISSUE TITLE
Payload ignore all properties except url

### ISSUE THREAD

**Issue by frizar** [apicase/core#9]
I just use basic example with simple changes:

```javascript
import { apicase } from '@apicase/core'
import fetch from '@apicase/adapter-fetch'

const doFetchRequest = apicase(fetch)

doFetchRequest({
  url: 'http://localhost:3000/users',
  method: 'POST',
  headers: { token: 'my_secret_token_123' },
  body: {
    some: 'data'
  }
 });
```

Expected result: POST request with data from body prop and token in headers
Real result: GET request with no body and no token in request headers.

I really enjoy how great this library, but it doesnt work properly for me :(
P.S. Axios works fine...

Sorry for my english.

**Comment by Kelin2025** [comment]
Hello! Thanks a lot for the issue!

It was my bad, `adapter.convert()` was used twice ([here](https://github.com/apicase/core/commit/8302254cecbafdfb5ae1b6c33bb533d8eaf45ac5#diff-b353c323e65c86a1c1128c7d1c2bfb76L89) and [here](https://github.com/apicase/core/commit/8302254cecbafdfb5ae1b6c33bb533d8eaf45ac5#diff-b353c323e65c86a1c1128c7d1c2bfb76L143))

Now it should be ok. Please, update `@apicase/core` package to `0.8.1` version.

**Comment by frizar** [comment]
Thanks, now it's better, but still no body in request.

**Comment by Kelin2025** [comment]
Hm. Ok, I added body preparation for fetch, here it is:  
![image](https://user-images.githubusercontent.com/4208480/37671904-ca7924d6-2c7d-11e8-9748-f3c91006bf3c.png)  
If you need, you can change this behaviour by passing `prepareBody` callback  
Update `@apicase/adapter-fetch` to `0.8.0` version

**Comment by frizar** [comment]
Now it's ok. I see body data in chrome dev tool. But... in my express app `req.body` is empty object `{}`...
Axios still work as expected... I am confused a bit :\

**Comment by Kelin2025** [comment]
Is question solved?

**Comment by frizar** [comment]
Still no... I tried it on fresh app. When i send post request to my express app `req.body` is `{}`, but `req.headers.token` is ok (`"my_secret_token_123"`).

**Comment by Kelin2025** [comment]
Have you tried to add `{ Accept: 'application/json'}` to headers?

**Comment by frizar** [comment]
OK, it should be `Content-Type: 'application/json'` also... Now my problem is solved. 
But i think this behaviour is not obvious.

**Comment by Kelin2025** [comment]
It looks like I should add it by default.. but maybe it's not obvious too :thinking:

**Comment by frizar** [comment]
Btw, thanks for help! How can i know that this will be changed?

**Comment by Kelin2025** [comment]
I'll write here if I'll add it (at least tomorrow, have a lot of work today)

**Comment by Kelin2025** [comment]
Time to drunk coding :beer:   
I added automatically passed `'Content-Type': 'application/json'` to headers if request body is a plain object. Update your fetch/xhr adapter to get this  
Also, I fixed critical bug with payload normalization in core package. Update `@apicase/core` as soon as possible (v0.9)

**Comment by frizar** [comment]
Thank you for help and for awesome library! I think it can be closed.
